Secure/Secure/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from bruteforce import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bruteforce.urls')),
]

Secure/bruteforce/urls.py
from django.urls import path,re_path
from bruteforce import views

app_name = 'bruteforce'

urlpatterns =[
    path('',views.index,name='index'),
    re_path(r'^register',views.register,name='register'),
]

Secure/bruteforce/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='bruteforce/profile_pics',blank =True)

    def __str__(self):
        return self.user.username

Secure/bruteforce/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Secure/bruteforce/views.py
from django.shortcuts import render
from bruteforce.models import UserProfileInfo
from bruteforce.forms import UserForm,UserProfileInfoForm

# Create your views here.



def index(request):
    return render(request,'bruteforce/index.html')

def register(request):
    
    registered = False
    if request.method =='POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)#hashing the password
            user.save() 

            profile =profile_form.save(commit=False)
            profile.user =user #OneToOne
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic'] #key defined in models
            profile.save()
            registered =True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'bruteforce/registration.html',{'user_form': user_form,
    'profile_form': profile_form,
    'registered':registered})




    

Secure/templates/bruteforce/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            
  
          <ul class="nav navbar-nav">
            <li><a href="{% url 'bruteforce:index' %}">HOME</a></li>
            <li><a href="{% url 'admin:index' %}">ADMINISTRATION</a></li>
            <li><a href="{% url 'bruteforce:register' %}">REGISTER</a></li>
          </ul>
        </div>
      </nav>

      {% block body %}
      {% endblock %}
    
</body>
</html>

Secure/templates/bruteforce/index.html
<!DOCTYPE html>
{% extends "bruteforce/base.html"%}
{% block body %}

<div>
    <h1>
        Home @ bruteforce.com  
    </h1>
</div>
{% endblock %}

Secure/templates/bruteforce/registration.html
<!DOCTYPE html>
{% extends "bruteforce/base.html" %}
{% load static %}

{% block body %}
<div>
    {% if registered %}
    <h1>Thanks for registering!</h1>
    {% else %}
    <h2>Register here:</h2>
    <h3>Fill out the form:</h3>
    <form method='POST'enctype ="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type ="submit" name="" value="register">
    </form>
    
{% endif %}
</div>
{% endblock %}